const { createUser, saveUser, getUserByTelegramId, getUserById, getUserByChannelId, deleteUser, setUserActive, updateUser } = require('./core');
const { getUsersByRegion, getUsersByRegionForScheduler, getAllActiveUsers, getAllUsers, getRecentUsers, getUsersWithRouterIp, getUsersWithActiveChannels, getUsersWithChannelsForVerification, getActiveUsersByRegionQueue, getActiveUsersWithReminders, paginateActiveUsers } = require('./queries');
const { updateUserPowerState, changePowerStateAndGetDuration, setPendingPowerChange, clearPendingPowerChange } = require('./power');
const { updateUserChannel, resetUserChannel, updateChannelBranding, updateChannelBrandingPartial, updateChannelStatus, updateUserChannelPaused } = require('./channel');
const { updateUserAlertSettings, updateUserFormatSettings, getUserFormatSettings, updateUserPowerNotifyTarget, updateScheduleAlertEnabled, updateScheduleAlertMinutes, updateScheduleAlertTarget, updateUserScheduleAlertSettings, updateNotificationSettings, updateChannelNotificationSettings, updateCleanupSettings } = require('./settings');
const { updateUserHash, updateUserPublishedHash, updateUserHashes, updateSnapshotHashes, getSnapshotHashes, batchUpdateHashes } = require('./hashes');
const { updateUserRegionQueue, updateUserRegionAndQueue, updateUserPostId, updateUserRouterIp, updateLastScheduleMessageId, updateLastBotKeyboardMessageId, updateLastReminderMessageId } = require('./updates');
const { getUserStats, getUserCount } = require('./stats');

module.exports = {
  createUser,
  saveUser,
  getUserByTelegramId,
  getUserById,
  getUserByChannelId,
  updateUserRegionQueue,
  updateUserRegionAndQueue,
  updateUserChannel,
  updateUserAlertSettings,
  updateUserHash,
  updateUserPublishedHash,
  updateUserHashes,
  updateUserPostId,
  setUserActive,
  getUsersByRegion,
  getAllActiveUsers,
  getAllUsers,
  getRecentUsers,
  getUserStats,
  deleteUser,
  updateUserRouterIp,
  updateUserPowerState,
  changePowerStateAndGetDuration,
  setPendingPowerChange,
  clearPendingPowerChange,
  getUsersWithRouterIp,
  resetUserChannel,
  updateChannelBranding,
  updateChannelBrandingPartial,
  updateChannelStatus,
  getUsersWithActiveChannels,
  getUsersWithChannelsForVerification,
  updateUserFormatSettings,
  getUserFormatSettings,
  updateLastScheduleMessageId,
  updateLastBotKeyboardMessageId,
  updateLastReminderMessageId,
  updateUserChannelPaused,
  updateUserPowerNotifyTarget,
  updateScheduleAlertEnabled,
  updateScheduleAlertMinutes,
  updateScheduleAlertTarget,
  updateUserScheduleAlertSettings,
  updateUser,
  updateSnapshotHashes,
  getSnapshotHashes,
  getUsersByRegionForScheduler,
  paginateActiveUsers,
  getActiveUsersByRegionQueue,
  batchUpdateHashes,
  getUserCount,
  updateNotificationSettings,
  updateChannelNotificationSettings,
  updateCleanupSettings,
  getActiveUsersWithReminders,
};
