module.exports = {
  // API
  API_TIMEOUT_MS: 30000,
  API_RETRY_DELAYS: [5000, 15000, 45000],
  API_MAX_RETRIES: 3,

  // Cache
  CACHE_TTL_MS: 2 * 60 * 1000,
  CACHE_MAX_SIZE: 100,
  CACHE_CLEANUP_INTERVAL_MS: 5 * 60 * 1000,

  // Scheduler
  DEFAULT_CHECK_INTERVAL_S: 60,
  SCHEDULER_STAGGER_MS: 50,
  SCHEDULER_MAX_PARALLEL_REGIONS: 5,

  // Telegram
  TELEGRAM_RATE_LIMIT_PER_SEC: 25,
  TELEGRAM_RETRY_AFTER_DEFAULT_MS: 5000,
  TELEGRAM_MAX_RETRIES: 3,

  // Power Monitor
  POWER_CHECK_INTERVAL_S: 2,
  POWER_DEBOUNCE_MINUTES: 5,
  POWER_MAX_CONCURRENT_PINGS: 50,
  POWER_PING_TIMEOUT_MS: 3000,

  // Cleanup
  PENDING_CHANNEL_CLEANUP_INTERVAL_MS: 60 * 60 * 1000,
  OLD_STATE_MAX_AGE_HOURS: 24,

  // Maps
  MAX_INSTRUCTION_MESSAGES_MAP_SIZE: 500,
  MAX_PENDING_CHANNELS_MAP_SIZE: 200,

  // Health
  POOL_STATS_LOG_INTERVAL_MS: 5 * 60 * 1000,
};
